name: deploy

on:
  push:
      # Dont want to trigger whole thing when updating readme etc
      paths-ignore:
        - README.md
        - .gitignore
      branches:
        - main

jobs:
  build_lint_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: install
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      # - name: deploy
      #   run: scp ./build/* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP }}:/home/homepage/site
      #   with:
      #     host: ${{ secrets.SSH_IP }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     password: ${{ secrets.SSH_PASSWORD }}
      - name: deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_RSA }}
          source: "./build"
          target: "/home/homepage/site"
